services:
  app:
    container_name: mm-prod
    image: iamjothees/mm:latest
    networks:
      - mm_internal
      - proxy_net
    restart: always
    environment:
      - TZ=${TZ:-Asia/Kolkata}
    volumes:
      - ./.env:/var/www/html/.env
  reverb:
    container_name: mm-prod-reverb
    image: iamjothees/mm:latest
    command: php artisan reverb:start --host=0.0.0.0 --port=8080
    networks:
      - mm_internal
      - proxy_net
    restart: always
    volumes:
      - ./.env:/var/www/html/.env

  db:
    container_name: mm-prod-db
    image: mysql:8.0
    restart: always
    environment:
      TZ: ${TZ:-Asia/Kolkata}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - mm_internal

  watchtower:
    image: containrrr/watchtower
    container_name: mm-watchtower
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      # Required if your Docker Hub repository is private
      - ~/.docker/config.json:/config.json
    environment:
      - WATCHTOWER_NOTIFICATIONS=shoutrrr
      # Replace this with your Slack, Discord, Telegram, or Email webhook URL
      - WATCHTOWER_NOTIFICATION_URL=${WATCHTOWER_WEBHOOK_URL}
      - WATCHTOWER_INCLUDE_STOPPED=true
      - WATCHTOWER_REVIVE_STOPPED=true
      - WATCHTOWER_CLEANUP=true
    command: --interval 60 mm-prod mm-prod-reverb

networks:
  mm_internal:
    driver: bridge
  proxy_net:
    external: true

volumes:
  db-data: