services:
  app:
    container_name: mm
    image: mm:latest
    volumes:
      - ./app:/var/www/html
    ports:
      - 8040:80
      - 8043:5173
    working_dir: /var/www/html
    networks:
      - tunnel_net
  reverb:
    container_name: mm-reverb
    image: mm:latest
    volumes:
      - ./app:/var/www/html
    ports:
      - 8041:8080
    working_dir: /var/www/html
    command: php artisan reverb:start --host=0.0.0.0 --port=8080
    networks:
      - tunnel_net
  db:
    container_name: mm-db
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: mm
      MYSQL_USER: mm
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    ports:
      - 8034:3306
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - tunnel_net
  # cloudflare-tunnel:
  #   image: cloudflare/cloudflared:latest
  #   container_name: cloudflared_tunnel
  #   restart: unless-stopped
  #   environment:
  #     - TUNNEL_TOKEN=
  #   command: tunnel --no-autoupdate run
  #   networks:
  #     - tunnel_net
networks:
  tunnel_net:
    driver: bridge
volumes:
  db-data:
